:toc: macro
:toc-title: Table of Contents
:toclevels: 99

# Signal

[link=https://app.codeship.com/projects/305030]
image::https://app.codeship.com/projects/8f6f0890-974c-0136-8b10-3a8748c13ef1/status?branch=master[Build Status]

This project deploys a partial working implementation of https://github.com/SensorUp/signal.

toc::[]

## Application

The application is a REST API deployed to AWS API Gateway.

The API defines one resource: `/menu`. The `GET /menu` method takes two query params, `ages` and `gender`, and returns a list of food portions that satisfies the recommended daily diet for an individual matching the query params.

Example request: https://8i4kebobg4.execute-api.us-west-2.amazonaws.com/production/menu?ages=19%20to%2030&gender=Female

## Architecture

### API

The API is implemented as a Lambda-backed REST API in AWS API Gateway. The Lambda functions are written in JavaScript (Nodejs 8.10). The API is deployed as a CloudFormation stack with fairly minimal configuration.

A proper data store for the API is not implemented. The data from the Signal CSV files is provided by stub "query" functions in the application code (see link:./src/sources[./src/sources]).

## CI/CD

The project uses CodeShip as the CI/CD pipeline. Codeship does not support public access to the project build log; I can add users on request.

In this simplified example project, the CI/CD pipeline runs some simple tests and deploys directly to an API Gateway stage called `production`. In a real-world project the pipeline would probably integrate with a branching/versioning protocol (eg, https://nvie.com/posts/a-successful-git-branching-model/[gitflow]), and therefore the next step would be to create separate branch-filtered pipelines for the development and release workflows.

### Testing

The unit test framework for the application is Mocha/Chai. See link:./test[./test].

Tests run in a disposable `signal-tester` container on Codeship. The Dockerfile for the container is in link:./docker/tester[./docker/tester] and the test steps are configured in link:codeship-steps.yml[codeship-steps.yml].

Tests have been implemented for `selectors/selectVegetablesAndFruit()`. The tests run on every commit, and they can be run locally by building the `tester` container.

### Deployment

Following each successful test run, the application deploys to AWS using a `signal-deployer` container running in Codeship. The deployer container uses Ansible playbooks to:
- package the source JavaScript and upload it to S3
- assert a CloudFormation stack for the Lambda and API resources
- trigger an API Gateway deployment

See link:./deploy[./deploy] for the Ansible/CloudFormation resources that the deployer container uses.

The deployer container depends on AWS credentials in link:./deploy/env.encrypted[./deploy/env.encrypted]. The credentials are encrypted with https://documentation.codeship.com/pro/builds-and-configuration/environment-variables/#encrypting-your-environment-variables[Jet].

## Project Management

This repo uses a https://github.com/vloun/signal/projects/1[basic Kanban project] to track and prioritize development tasks. Commit messages reference issue numbers on the project board.

## Things Not Done

In this project, I gave priority to the following elements:

- a working testing/deployment pipeline
- infrastructure as code
- out-of-the-box scalability

As a result I've more or less ignored a number of important considerations in the application design:

- modelling, data normalization
- branching (eg, gitflow)
- more expressive API resources
- error handling
- a proper database
- documentation

## Review

### How to Inspect the Deployed Project

#### API

The base URL for the deployed API is https://8i4kebobg4.execute-api.us-west-2.amazonaws.com/production

You can query the `/menu` resource with the following request syntax:

`GET https://8i4kebobg4.execute-api.us-west-2.amazonaws.com/production/menu?ages={ age_value }&gender={ gender_value }`

Where

- `{ age_value }` is any value from the `ages` column
- `{ gender_value }` is any value from the `gender` column

of https://github.com/SensorUp/signal/blob/master/data/servings_per_day-en_ONPP.csv

#### AWS Stack, Codeship Project

To view the running AWS stack and Codeship build project, you'll need account access. I can set that up.


### How to Run Your Own Copy

1. Fork the repository
2. Get a Codeship account (they are free) and associate your repo fork with a new Pro (ie, docker-based) build project.
3. Get an AWS account.
4. In the AWS account, create a `signal-deployment` user. Give it the permissions listed on link:aws_policy.md[aws_policy.md].
5. Generate a set of API access keys for the `signal-deployment` user and save them to a text file called *./deploy/env*, in the following format:

        AWS_ACCESS_KEY_ID=XXXXXXXXXXXXXXXXXXX
        AWS_SECRET_ACCESS_KEY=YYYYYYYYYYYYYYYYYYYYYYYY

6. https://documentation.codeship.com/pro/builds-and-configuration/environment-variables/#encrypting-your-environment-variables[Encrypt the env file]. The encrypted file should replace the existing file at link:./deploy/env.encrypted[./deploy/env.encrypted]
7. Pick a unique name for the deployment S3 bucket, and update the link:./deploy/ansible/group_vars/all.yml#L6[`lambda_source_s3_bucket` variable here].
8. Commit and push your changes to */deploy/env.encrypted* and */deploy/ansible/group_vars/all.yml*. The build should run in your Codeship project, and deploy the API stack to AWS.
9. Go to the API Gateway console and grab your API URL. Try it out!
